### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by ruffmeister69** [holdestmade/SmartThingsYeelight#1]
Defo have e right IP added and have created the handler and the device but bulb will not turn on but still works inside the mihome app

**Comment by holdestmade** [comment]
Have you turned on LAN Control in the Yeelight APP ?

**Comment by kevinmirsky** [comment]
I'm experiencing this issue as well. I thought LAN control was the issue, but enabling it didn't resolve the problem. LAN control works as I've tested it with Yeelight's Windows demo...

Let me list my steps as best I can and perhaps that might help spot where I went wrong (and hopefully ruffmaster too):

1. Select my home on the web interface
2. Go to "My device Handlers" and create from code
3. Copy code from Github file and paste in
4.  Hit Create
5. Publish > For me ( I've done this as I saw it in another video about custom device handlers and figured that was the issue, but doesn't seem to be)
6.  Go to "My Devices"
7. Create new device, using the new "Yeelight" as device type. I add it to my Home and Hub. I set something like  "myLamp" as the ID.
8. I go into the Classic Android app, enter the light's menu, and select the gear, entering the local IPv4 address for the bulb (confirmed in Yeelight app)
9. Go back and attempt to turn on or off. Light does not change.

I'm really not sure where something's gone wrong. I'm not too familiar with the custom automation handlers, so I wouldn't be surprised if I hit the wrong setting or such.

 I'm using a 2nd Gen RGB bulb. The hub itself is working as I've configured a Smartthings button to use IFTTT to toggle the bulb for the time being.

**Comment by mericyoung** [comment]
I'm actually having the exact same issue.

**Comment by holdestmade** [comment]
In the device settings in the ST IDE, is the Device Network Id set to the hex of the IP and port ? For some reason this is not getting populated. Try converting the IP to hex (4 hex pairs) and use port D893. Eg. 192.168.1.99 would be c0a80163:d893

**Comment by l0gikz** [comment]
Worked! Thanks for the quick reply.

**Comment by holdestmade** [comment]
If you uncomment out line 177, the hex IP will be shown in the log when you try to send a command

**Comment by kevinmirsky** [comment]
Can also confirm this works! Many thanks!

**Comment by holdestmade** [comment]
I've updated the code to automatically fill in the device network ID, so on creation of the device just put random in the field and when you turn the bulb on/off for first time it will populate it.

**Comment by l0gikz** [comment]
Yep it worked! Thanks!!
