### ISSUE TITLE
works with v3 ?

### ISSUE THREAD

**Issue by bensil1** [holdestmade/SmartThingsYeelight#3]
i get
Access Denied
We're sorry, but you are not authorized to perform the requested operation.

help :-(

**Comment by holdestmade** [comment]
Not sure, not got any v3 models to try. There is only one Yeelight API for all their products so no reason it shouldn;t work if you have it working in the Yeelight APP and enabled LAN Control

**Comment by bensil1** [comment]
i did enabled LAN Control
same messag 
Access Denied
We're sorry, but you are not authorized to perform the requested operation.

**Comment by holdestmade** [comment]
Where are you getting the error message ?

Can you install Packet Sender and add this to the ASCII field:

`{"id": 1, "method": "set_power", "params":["on", "smooth", 500]}\r\n`

This should turn the bulb on

Don’t forget to fill in the IP address of the bulb and the port number to 55443 and change to TCP.

If you get a reply in the bottom of the window can you copy and paste it back to me ? It should be: `{“id”:1, “result”:[“ok”]}\r\n`

**Comment by bensil1** [comment]
the error message is after tring to add divice in graph-eu01-....

**Comment by holdestmade** [comment]
Closed
